
# get data from config server...
server:
  port: 9001
  shutdown: graceful # enable graceful shutdown
  tomcat:
    connection-timeout: 2s # default is 20s, prevent Dos attacks where a connection is established, TOmcat reserves a thread to handle
                          # and the request never comes
    keep-alive-timeout: 15s # how long keep a connection open while waiting for new requests
    threads: # default can grow up to 20 threads and has 1 worker threads always running
      max: 50
      min-spare: 5

spring:
  application:
    name: catalog-service
    # when the integration with the config server is not optional,
    # the app fails to start up if it cannot contact a config server
  lifecycle:
    timeout-per-shutdown-phase: 15s # defulat is 30 s
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000 # 5s
      request-read-timeout: 5000
      fail-fast: false # in prod, setto true
      # retry behavior is enabled only when the fail-fast is set to true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    # spring boot uses HikariCP for connection pooling
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  # nu default, spring data loads the "schema.sql" file only when using an embedded in-memory db
  # so we need to enable this functionality
  #sql:
  #  init:
  #    mode: alway
  flyway:
    baselineOnMigrate: true
# refresh event -> RefreshScopeRefreshedEvent will have no effect if there is no component
#   listening. You can use @RefreshScope annotation on any bean you would like to be reloaded
# whenever  a refresh is triggered
# but #ConfigurationProperties is already listening to RefreshScopeREfreshedEvent by default
# trigger a refresh -> http POST :9001/actuator/refresh
management:
  endpoints:
    web:
      exposure:
        include: refresh

polar:
  greeting: Welcome to the local book catalog!