apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service # name of the Deployment
  labels: # set of labels attached to the DEployment
    app: catalog-service
spec: # spec section contains a selector part to define a strategy for identyfing which objects should be scaled by ReplicaSet
  replicas: 1
  selector: # defines the labels used to select the Pods to be scaled
    matchLabels:
      app: catalog-service
  template: # template part describes the specification for creating the desired Pod and Containers
    metadata:
      labels: # labels attached to the Pod object - should match the ones used as selectors
        app: catalog-service
    spec:
      containers:
        - name: catalog-service # name of the Pod
          image: catalog-service
          imagePullPolicy: IfNotPresent # pull the image from container registry only if its not present locally yet
          lifecycle: # graceful shutdown.. delay the SIGTERM signal by 5 seconds
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9001
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://polar-postgres/polardb_catalog # polar-postgres is the name through which other objects in the cluster
                                                                      # can communicate with PostgreSl instance
            - name: SPRING_PROFILES_ACTIVE
              value: testdata