apiVersion: v1
kind: Service
metadata:
  name: catalog-service # name of the service
  labels:  # labels attaached to the service
    app: catalog-service
spec:
  type: ClusterIP
  selector: # the label used to match the Pods to target and expose
    app: catalog-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9001